baseURL = 'https://oalvaroaqui.xyz/'
languageCode = 'pt-br'
title = 'Dev & Ops Blog'
theme = 'PaperMod'

[params]
    defaultTheme = "auto"
    showCodeCopyButtons = true

    [params.profileMode]
        enabled = true
        title = "√Ålvaro"
        subtitle = "Estudante de .NET, Kubernetes e Monitoramento"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/oalvaroaqui-git"

    [[params.socialIcons]]
        name = "linkedin"
        url = "https://linkedin.com/in/seu-usuario"